name: update-plugin-metadata

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  extract:
    uses: FAIRmat-NFDI/nomad-plugins-metadata/.github/workflows/extract-plugin-metadata.yml@main
    permissions:
      contents: write
    with:
      package_spec: nomad-plugins-metadata==0.1.0
      auto_commit: true
